import { useState, useEffect, useCallback, useRef } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Flame, AtSign, Check, X, Loader2 } from "lucide-react";
import { useLocale } from "@/contexts/LocaleContext";

const USERNAME_REGEX = /^[a-zA-Z0-9_]{3,20}$/;
const isAutoGenerated = (u: string | null) => !u || u.startsWith("user_");

const UsernameGuard = ({ children }: { children: React.ReactNode }) => {
  const { user } = useAuth();
  const { t } = useLocale();
  const [username, setUsername] = useState("");
  const [hasUsername, setHasUsername] = useState<boolean | null>(null);
  const [checking, setChecking] = useState(false);
  const [available, setAvailable] = useState<boolean | null>(null);
  const [saving, setSaving] = useState(false);
  const retryCount = useRef(0);

  useEffect(() => {
    if (!user) return;
    let cancelled = false;

    const checkProfile = async () => {
      const { data } = await supabase
        .from("profiles")
        .select("username")
        .eq("user_id", user.id)
        .single();

      if (cancelled) return;

      if (!data) {
        if (retryCount.current < 5) {
          retryCount.current++;
          setTimeout(checkProfile, 800);
          return;
        }
        setHasUsername(false);
        return;
      }

      setHasUsername(!isAutoGenerated(data.username));
    };

    checkProfile();
    return () => { cancelled = true; };
  }, [user]);

  useEffect(() => {
    if (!USERNAME_REGEX.test(username)) {
      setAvailable(null);
      return;
    }
    setChecking(true);
    const timer = setTimeout(async () => {
      const { data } = await supabase
        .from("profiles")
        .select("user_id")
        .ilike("username", username)
        .limit(1);
      setAvailable(!data || data.length === 0);
      setChecking(false);
    }, 400);
    return () => clearTimeout(timer);
  }, [username]);

  const handleConfirm = useCallback(async () => {
    if (!user || !available) return;
    setSaving(true);

    const { error } = await supabase
      .from("profiles")
      .update({ username: username.toLowerCase() })
      .eq("user_id", user.id);

    if (error) {
      setSaving(false);
      return;
    }
    setHasUsername(true);
  }, [user, username, available]);

  if (hasUsername === null) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="w-8 h-8 text-primary animate-spin" />
      </div>
    );
  }

  if (hasUsername) return <>{children}</>;

  const isValid = USERNAME_REGEX.test(username);
  const canConfirm = isValid && available && !checking && !saving;

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-6 bg-background">
      <Flame className="w-10 h-10 text-primary mb-4" />
      <h1 className="text-2xl font-display font-bold mb-2">{t('username.chooseUsername')}</h1>
      <p className="text-sm text-muted-foreground text-center mb-8">
        {t('username.usernameDesc')}
      </p>

      <div className="w-full max-w-xs space-y-4">
        <div className="relative">
          <AtSign className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
          <Input
            value={username}
            onChange={(e) => setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, ""))}
            placeholder={t('username.placeholder')}
            className="h-12 pl-11 bg-secondary border-border rounded-xl pr-10"
            maxLength={20}
            autoFocus
          />
          {isValid && !checking && available !== null && (
            <div className="absolute right-3 top-1/2 -translate-y-1/2">
              {available ? (
                <Check className="w-5 h-5 text-primary" />
              ) : (
                <X className="w-5 h-5 text-destructive" />
              )}
            </div>
          )}
          {checking && (
            <Loader2 className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground animate-spin" />
          )}
        </div>

        <p className="text-xs text-muted-foreground">
          {t('username.rules')}
        </p>

        {isValid && available === false && (
          <p className="text-xs text-destructive">{t('username.taken')}</p>
        )}

        <Button
          onClick={handleConfirm}
          disabled={!canConfirm}
          className="w-full h-14 text-lg font-display font-bold bg-gradient-primary text-primary-foreground hover:opacity-90 shadow-glow rounded-xl"
        >
          {saving ? <Loader2 className="w-5 h-5 animate-spin" /> : t('username.confirm')}
        </Button>
      </div>
    </div>
  );
};

export default UsernameGuard;
